sudo: required
language: generic
services:
  - docker

script:
  - docker build -t weboaks/node-karma-protractor-chrome:debian-root-$(git rev-parse HEAD) .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push weboaks/node-karma-protractor-chrome:debian-root-$(git rev-parse HEAD)
